[package]
name = "arkgan"
version = "0.0.8"
edition = "2021"
authors = ["Ravinthiran Partheepan <ravinthiranpartheepan@gmail.com>"]
documentation = "https://docs.rs/arkgan/latest/arkgan/"
description = "An open source GAN toolkit"
license = "Apache-2.0"

[lib]
name = "arkgan"
path = "./src/lib.rs"

